### ISSUE TITLE
problem draging to empty recyclerview list

### ISSUE THREAD

**Issue by manchiez** [pooja-gaikwad15/recyclerview-list-drag-and-drop#1]

**Comment by pooja-gaikwad15** [comment]
@manchiez  - Can you please describe the issue more specifically?

**Comment by pooja-gaikwad15** [comment]
@manchiez - Hi, I have updated the code with an **Empty View** for one of the list. You can reuse the same logic if you require Empty Views for both the lists. I hope your issue is resolved. Thanks.
